-- +goose Up

CREATE SCHEMA bagicore;

-- Language

CREATE TABLE bagicore.language (
    id              bigint                      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamp with time zone    NOT NULL DEFAULT timezone('UTC', now()),
    updated_at      timestamp with time zone,

    ietf            text                        NOT NULL,
    name            text                        NOT NULL
);

ALTER TABLE ONLY bagicore.language ADD CONSTRAINT language_ietf_key
    UNIQUE (ietf);

ALTER TABLE ONLY bagicore.language ADD CONSTRAINT language_ietf_check
    CHECK (ietf <> '' AND length(ietf) <= 12);
ALTER TABLE ONLY bagicore.language ADD CONSTRAINT language_name_check
    CHECK (name <> '' AND length(name) <= 24);

-- Website

CREATE TABLE bagicore.website (
    id              bigint                      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamp with time zone    NOT NULL DEFAULT timezone('UTC', now()),
    updated_at      timestamp with time zone,

    domain          text                        NOT NULL,
    name            text                        NOT NULL,
    machine_tl      boolean
);

ALTER TABLE ONLY bagicore.website ADD CONSTRAINT website_domain_key
    UNIQUE (domain);

ALTER TABLE ONLY bagicore.website ADD CONSTRAINT website_domain_check
    CHECK (domain <> '' AND length(domain) <= 32);
ALTER TABLE ONLY bagicore.website ADD CONSTRAINT website_name_check
    CHECK (name <> '' AND length(name) <= 48);

-- Website TLLanguage

CREATE TABLE bagicore.website_tllanguage (
    created_at      timestamp with time zone    NOT NULL DEFAULT timezone('UTC', now()),
    updated_at      timestamp with time zone,

    website_id      bigint                      NOT NULL,
    language_id     bigint                      NOT NULL
);

ALTER TABLE ONLY bagicore.website_tllanguage ADD CONSTRAINT website_tllanguage_pkey
    PRIMARY KEY (website_id, language_id);

ALTER TABLE ONLY bagicore.website_tllanguage ADD CONSTRAINT website_tllanguage_website_id_fkey
    FOREIGN KEY (website_id) REFERENCES bagicore.website(id) ON DELETE CASCADE;
ALTER TABLE ONLY bagicore.website_tllanguage ADD CONSTRAINT website_tllanguage_language_id_fkey
    FOREIGN KEY (language_id) REFERENCES bagicore.language(id) ON DELETE CASCADE;

-- Link

CREATE TABLE bagicore.link (
    id              bigint                      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamp with time zone    NOT NULL DEFAULT timezone('UTC', now()),
    updated_at      timestamp with time zone,

    website_id      bigint                      NOT NULL,
    relative_url    text                        NOT NULL,
    machine_tl      boolean
);

ALTER TABLE ONLY bagicore.link ADD CONSTRAINT link_website_id_fkey
    FOREIGN KEY (website_id) REFERENCES bagicore.website(id) ON DELETE CASCADE;

ALTER TABLE ONLY bagicore.link ADD CONSTRAINT link_website_id_relative_url_key
    UNIQUE (website_id, relative_url);

ALTER TABLE ONLY bagicore.link ADD CONSTRAINT link_relative_url_check
    CHECK (relative_url <> '' AND length(relative_url) <= 128);

-- Link TLLanguage

CREATE TABLE bagicore.link_tllanguage (
    created_at      timestamp with time zone    NOT NULL DEFAULT timezone('UTC', now()),
    updated_at      timestamp with time zone,

    link_id         bigint                      NOT NULL,
    language_id     bigint                      NOT NULL
);

ALTER TABLE ONLY bagicore.link_tllanguage ADD CONSTRAINT link_tllanguage_pkey
    PRIMARY KEY (link_id, language_id);

ALTER TABLE ONLY bagicore.link_tllanguage ADD CONSTRAINT link_tllanguage_link_id_fkey
    FOREIGN KEY (link_id) REFERENCES bagicore.link(id) ON DELETE CASCADE;
ALTER TABLE ONLY bagicore.link_tllanguage ADD CONSTRAINT link_tllanguage_language_id_fkey
    FOREIGN KEY (language_id) REFERENCES bagicore.language(id) ON DELETE CASCADE;

-- Comic

CREATE TABLE bagicore.comic (
    id              bigint                      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamp with time zone    NOT NULL DEFAULT timezone('UTC', now()),
    updated_at      timestamp with time zone,

    code            text                        NOT NULL
);

ALTER TABLE ONLY bagicore.comic ADD CONSTRAINT comic_code_key
    UNIQUE (code);

ALTER TABLE ONLY bagicore.comic ADD CONSTRAINT comic_code_check
    CHECK (length(code) = 8);

-- Comic Link

CREATE TABLE bagicore.comic_link (
    created_at      timestamp with time zone    NOT NULL DEFAULT timezone('UTC', now()),
    updated_at      timestamp with time zone,

    comic_id        bigint                      NOT NULL,
    link_id         bigint                      NOT NULL
);

ALTER TABLE ONLY bagicore.comic_link ADD CONSTRAINT comic_link_pkey
    PRIMARY KEY (comic_id, link_id);

ALTER TABLE ONLY bagicore.comic_link ADD CONSTRAINT comic_link_comic_id_fkey
    FOREIGN KEY (comic_id) REFERENCES bagicore.comic(id) ON DELETE CASCADE;
ALTER TABLE ONLY bagicore.comic_link ADD CONSTRAINT comic_link_link_id_fkey
    FOREIGN KEY (link_id) REFERENCES bagicore.link(id) ON DELETE CASCADE;

-- Comic Chapter

CREATE TABLE bagicore.comic_chapter (
    id              bigint                      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamp with time zone    NOT NULL DEFAULT timezone('UTC', now()),
    updated_at      timestamp with time zone,

    comic_id        bigint                      NOT NULL,
    chapter         text                        NOT NULL,
    version         text,
    released_at     timestamp with time zone    NOT NULL
);

ALTER TABLE ONLY bagicore.comic_chapter ADD CONSTRAINT comic_chapter_comic_id_fkey
    FOREIGN KEY (comic_id) REFERENCES bagicore.comic(id) ON DELETE CASCADE;

CREATE UNIQUE INDEX comic_chapter_comic_id_chapter_version_key ON bagicore.comic_chapter
    (comic_id, COALESCE(chapter, ''), COALESCE(version, ''));

ALTER TABLE ONLY bagicore.comic_chapter ADD CONSTRAINT comic_chapter_chapter_check
    CHECK (chapter <> '' AND length(chapter) <= 64);
ALTER TABLE ONLY bagicore.comic_chapter ADD CONSTRAINT comic_chapter_version_check
    CHECK (version <> '' AND length(version) <= 32);

-- Comic Chapter Link

CREATE TABLE bagicore.comic_chapter_link (
    created_at      timestamp with time zone    NOT NULL DEFAULT timezone('UTC', now()),
    updated_at      timestamp with time zone,

    chapter_id      bigint                      NOT NULL,
    link_id         bigint                      NOT NULL
);

ALTER TABLE ONLY bagicore.comic_chapter_link ADD CONSTRAINT comic_chapter_link_pkey
    PRIMARY KEY (chapter_id, link_id);

ALTER TABLE ONLY bagicore.comic_chapter_link ADD CONSTRAINT comic_chapter_link_chapter_id_fkey
    FOREIGN KEY (chapter_id) REFERENCES bagicore.comic_chapter(id) ON DELETE CASCADE;
ALTER TABLE ONLY bagicore.comic_chapter_link ADD CONSTRAINT comic_chapter_link_link_id_fkey
    FOREIGN KEY (link_id) REFERENCES bagicore.link(id) ON DELETE CASCADE;

-- +goose Down

DROP TABLE bagicore.comic_chapter_link;
DROP TABLE bagicore.comic_chapter;
DROP TABLE bagicore.comic_link;
DROP TABLE bagicore.comic;
DROP TABLE bagicore.link_tllanguage;
DROP TABLE bagicore.link;
DROP TABLE bagicore.website_tllanguage;
DROP TABLE bagicore.website;
DROP TABLE bagicore.language;
DROP SCHEMA bagicore;
